user:
  outputs:
    default:
      account: OSTYVCD-TE15074
      auth_type: password
      client_session_keep_alive: false
      connect_retries: 3
      connect_timeout: 30
      database: ECOMMERCE_DB
      password: mohdAtif@123456
      retry_on_database_errors: true
      role: null
      schema: dbt_mohdatif812
      threads: 6
      type: snowflake
      user: mohdatif
      warehouse: compute_wh
  target: default
