version: 2

models:

  - name: dim_customer
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: dim_product
    columns:
      - name: product_id
        tests:
          - unique
          - not_null

  - name: dim_store
    columns:
      - name: store_id
        tests:
          - unique
          - not_null

  - name: dim_vendor
    columns:
      - name: vendor_id
        tests:
          - unique
          - not_null

  - name: dim_warehouse
    columns:
      - name: warehouse_id
        tests:
          - unique
          - not_null

  - name: dim_delivery_partner
    columns:
      - name: partner_id
        tests:
          - unique
          - not_null